version: '3.8'

services:
  db:
    image: mysql
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: products
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev
  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8787:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www  
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: